Repository LikeLion13-Team4/Team4-BackEnd, pull requests merged in 2025-07, with the labels that each got.

#7 Feat/#4 jwt 인증 인가 구현 및 auth 일부 기능 구현
  build.gradle
  src/main/java/com/project/team4backend/domain/auth/contoller/AuthController.java
  src/main/java/com/project/team4backend/domain/auth/dto/request/AuthReqDTO.java
  src/main/java/com/project/team4backend/domain/auth/dto/response/AuthResDTO.java
  src/main/java/com/project/team4backend/domain/auth/entity/Auth.java
  src/main/java/com/project/team4backend/domain/auth/entity/IsTempPassword.java
  src/main/java/com/project/team4backend/domain/auth/entity/Token.java
  src/main/java/com/project/team4backend/domain/auth/exception/AuthErrorCode.java
  src/main/java/com/project/team4backend/domain/auth/exception/AuthException.java
  src/main/java/com/project/team4backend/domain/auth/repository/AuthRepository.java
  src/main/java/com/project/team4backend/domain/auth/service/RefreshTokenService.java
  src/main/java/com/project/team4backend/domain/auth/service/command/AuthCommandService.java
  src/main/java/com/project/team4backend/domain/auth/service/command/AuthCommandServiceImpl.java
  src/main/java/com/project/team4backend/domain/member/entity/Gender.java
  src/main/java/com/project/team4backend/domain/member/entity/Member.java
  src/main/java/com/project/team4backend/domain/member/entity/Role.java
  src/main/java/com/project/team4backend/global/BaseEntity.java
  src/main/java/com/project/team4backend/global/security/Config/CorsConfig.java
  src/main/java/com/project/team4backend/global/security/Config/RedisConfig.java
  src/main/java/com/project/team4backend/global/security/Config/SecurityConfig.java
  src/main/java/com/project/team4backend/global/security/CustomUserDetails.java
  src/main/java/com/project/team4backend/global/security/CustomUserDetailsService.java
  src/main/java/com/project/team4backend/global/security/JwtUtil.java
  src/main/java/com/project/team4backend/global/security/filter/CustomLoginFilter.java
  src/main/java/com/project/team4backend/global/security/filter/ForcePasswordChangeFilter.java
  src/main/java/com/project/team4backend/global/security/filter/JwtAuthorizationFilter.java
  src/main/java/com/project/team4backend/global/security/handler/CustomLogoutHandler.java
  src/main/java/com/project/team4backend/global/security/handler/CustomLogoutSuccessHandler.java
  src/main/java/com/project/team4backend/global/security/handler/JwtAccessDeniedHandler.java
  src/main/java/com/project/team4backend/global/security/handler/JwtAuthenticationEntryPoint.java
Labels: ✨feature

#12 ♻️refactor: Entity 코드 리팩토링 및 enums 클래스 패키지 이동
  src/main/java/com/project/team4backend/Team4BackEndApplication.java
  src/main/java/com/project/team4backend/domain/auth/entity/Auth.java
  src/main/java/com/project/team4backend/domain/auth/entity/EmailVerification.java
  src/main/java/com/project/team4backend/domain/auth/entity/SocialLogin.java
  src/main/java/com/project/team4backend/domain/auth/entity/Token.java
  src/main/java/com/project/team4backend/domain/auth/entity/Type.java
  src/main/java/com/project/team4backend/domain/auth/entity/enums/IsTempPassword.java
  src/main/java/com/project/team4backend/domain/auth/entity/enums/Type.java
  src/main/java/com/project/team4backend/domain/comment/entity/Comment.java
  src/main/java/com/project/team4backend/domain/comment/entity/CommentLike.java
  src/main/java/com/project/team4backend/domain/meal/entity/Meal.java
  src/main/java/com/project/team4backend/domain/meal/entity/MealCheck.java
  src/main/java/com/project/team4backend/domain/meal/entity/NutritionInfo.java
  src/main/java/com/project/team4backend/domain/member/entity/Gender.java
  src/main/java/com/project/team4backend/domain/member/entity/Member.java
  src/main/java/com/project/team4backend/domain/member/entity/Role.java
  src/main/java/com/project/team4backend/domain/member/entity/enums/Gender.java
  src/main/java/com/project/team4backend/domain/member/entity/enums/Role.java
  src/main/java/com/project/team4backend/domain/post/entity/Post.java
  src/main/java/com/project/team4backend/domain/post/entity/PostTag.java
  src/main/java/com/project/team4backend/domain/post/entity/Tag.java
  src/main/java/com/project/team4backend/domain/report/entity/GPTFeedback.java
  src/main/java/com/project/team4backend/domain/report/entity/Report.java
  src/main/java/com/project/team4backend/global/security/CustomUserDetails.java
  src/main/java/com/project/team4backend/global/security/JwtUtil.java
  src/main/java/com/project/team4backend/global/security/filter/ForcePasswordChangeFilter.java
  src/main/java/com/project/team4backend/global/security/filter/JwtAuthorizationFilter.java
Labels: ♻️refactor

#13 Feat/#5 회원가입 로그인 로그아웃 기능 구현
  build.gradle
  src/main/java/com/project/team4backend/domain/auth/contoller/AuthController.java
  src/main/java/com/project/team4backend/domain/auth/contoller/EmailVerificationController.java
  src/main/java/com/project/team4backend/domain/auth/converter/AuthConverter.java
  src/main/java/com/project/team4backend/domain/auth/converter/EmailVerificationConverter.java
  src/main/java/com/project/team4backend/domain/auth/dto/request/AuthReqDTO.java
  src/main/java/com/project/team4backend/domain/auth/dto/request/EmailVerificationReqDTO.java
  src/main/java/com/project/team4backend/domain/auth/dto/response/AuthResDTO.java
  src/main/java/com/project/team4backend/domain/auth/entity/EmailVerification.java
  src/main/java/com/project/team4backend/domain/auth/entity/enums/Type.java
  src/main/java/com/project/team4backend/domain/auth/exception/auth/AuthErrorCode.java
  src/main/java/com/project/team4backend/domain/auth/exception/auth/AuthException.java
  src/main/java/com/project/team4backend/domain/auth/exception/email/EmailVerificationErrorCode.java
  src/main/java/com/project/team4backend/domain/auth/exception/email/EmailVerificationException.java
  src/main/java/com/project/team4backend/domain/auth/repository/EmailVerificationRepository.java
  src/main/java/com/project/team4backend/domain/auth/service/EmailTemplateBuilder.java
  src/main/java/com/project/team4backend/domain/auth/service/command/AuthCommandService.java
  src/main/java/com/project/team4backend/domain/auth/service/command/AuthCommandServiceImpl.java
  src/main/java/com/project/team4backend/domain/auth/service/command/auth/AuthCommandService.java
  src/main/java/com/project/team4backend/domain/auth/service/command/auth/AuthCommandServiceImpl.java
  src/main/java/com/project/team4backend/domain/auth/service/command/email/EmailVerificationCommandService.java
  src/main/java/com/project/team4backend/domain/auth/service/command/email/EmailVerificationCommandServiceImpl.java
  src/main/java/com/project/team4backend/domain/auth/service/query/AuthQueryService.java
  src/main/java/com/project/team4backend/domain/auth/service/query/AuthQueryServiceImpl.java
  src/main/java/com/project/team4backend/domain/auth/service/scheduler/EmailVerificationScheduler.java
  src/main/java/com/project/team4backend/domain/comment/entity/Comment.java
  src/main/java/com/project/team4backend/domain/member/contoller/MemberController.java
  src/main/java/com/project/team4backend/domain/member/converter/MemberConverter.java
  src/main/java/com/project/team4backend/domain/member/dto/request/MemberReqDTO.java
  src/main/java/com/project/team4backend/domain/member/dto/response/MemberResDTO.java
  src/main/java/com/project/team4backend/domain/member/exception/MemberErrorCode.java
  src/main/java/com/project/team4backend/domain/member/exception/MemberException.java
  src/main/java/com/project/team4backend/domain/member/repository/MemberRepository.java
  src/main/java/com/project/team4backend/domain/member/service/command/MemberCommandService.java
  src/main/java/com/project/team4backend/domain/member/service/command/MemberCommandServiceImpl.java
  src/main/java/com/project/team4backend/domain/member/service/query/MemberQueryService.java
  src/main/java/com/project/team4backend/domain/member/service/query/MemberQueryServiceImpl.java
  src/main/java/com/project/team4backend/global/security/Config/SecurityConfig.java
  src/main/java/com/project/team4backend/global/security/JwtUtil.java
  src/main/java/com/project/team4backend/global/security/filter/CustomLoginFilter.java
  src/main/java/com/project/team4backend/global/security/filter/ForcePasswordChangeFilter.java
  src/main/java/com/project/team4backend/global/security/handler/CustomLogoutHandler.java
  src/main/java/com/project/team4backend/global/security/handler/CustomLogoutSuccessHandler.java
  src/main/java/com/project/team4backend/global/security/handler/JwtAccessDeniedHandler.java
  src/main/java/com/project/team4backend/global/security/handler/JwtAuthenticationEntryPoint.java
Labels: ✨feature

#23 Feat/#11 비밀번호 변경 임시 비밀번호 발급 api 구현
  src/main/java/com/project/team4backend/domain/auth/contoller/AuthController.java
  src/main/java/com/project/team4backend/domain/auth/contoller/EmailVerificationController.java
  src/main/java/com/project/team4backend/domain/auth/converter/EmailVerificationConverter.java
  src/main/java/com/project/team4backend/domain/auth/dto/request/AuthReqDTO.java
  src/main/java/com/project/team4backend/domain/auth/dto/request/EmailVerificationReqDTO.java
  src/main/java/com/project/team4backend/domain/auth/entity/Auth.java
  src/main/java/com/project/team4backend/domain/auth/entity/EmailVerification.java
  src/main/java/com/project/team4backend/domain/auth/exception/auth/AuthErrorCode.java
  src/main/java/com/project/team4backend/domain/auth/exception/email/EmailVerificationErrorCode.java
  src/main/java/com/project/team4backend/domain/auth/repository/EmailVerificationRepository.java
  src/main/java/com/project/team4backend/domain/auth/service/command/auth/AuthCommandService.java
  src/main/java/com/project/team4backend/domain/auth/service/command/auth/AuthCommandServiceImpl.java
  src/main/java/com/project/team4backend/domain/auth/service/command/email/EmailVerificationCommandService.java
  src/main/java/com/project/team4backend/domain/auth/service/command/email/EmailVerificationCommandServiceImpl.java
  src/main/java/com/project/team4backend/domain/member/exception/MemberErrorCode.java
  src/main/java/com/project/team4backend/global/security/filter/CustomLoginFilter.java
  src/main/java/com/project/team4backend/global/security/filter/ForcePasswordChangeFilter.java
  src/main/java/com/project/team4backend/global/security/handler/CustomLogoutHandler.java
  src/main/java/com/project/team4backend/global/security/handler/JwtAccessDeniedHandler.java
  src/main/java/com/project/team4backend/global/security/handler/JwtAuthenticationEntryPoint.java
Labels: ✨feature

#29 Feat/#14 댓글 좋아요기능 제한
  src/main/java/com/project/team4backend/domain/comment/controller/CommentController.java
  src/main/java/com/project/team4backend/domain/comment/entity/CommentLike.java
  src/main/java/com/project/team4backend/domain/comment/exception/CommentErrorCode.java
  src/main/java/com/project/team4backend/domain/comment/repository/CommentLikeRepository.java
  src/main/java/com/project/team4backend/domain/comment/repository/CommentRepository.java
  src/main/java/com/project/team4backend/domain/comment/service/command/CommentCommandService.java
  src/main/java/com/project/team4backend/domain/comment/service/command/CommentCommandServiceImpl.java
  src/main/java/com/project/team4backend/domain/comment/service/query/CommentQueryServiceImpl.java
Labels: ✨feature

#26 Feat/#12 내 정보 조회 수정 회원 탈퇴 api 구현
  src/main/java/com/project/team4backend/domain/auth/converter/AuthConverter.java
  src/main/java/com/project/team4backend/domain/auth/entity/Auth.java
  src/main/java/com/project/team4backend/domain/auth/repository/AuthRepository.java
  src/main/java/com/project/team4backend/domain/member/contoller/MemberController.java
  src/main/java/com/project/team4backend/domain/member/converter/MemberConverter.java
  src/main/java/com/project/team4backend/domain/member/dto/request/MemberReqDTO.java
  src/main/java/com/project/team4backend/domain/member/entity/Member.java
  src/main/java/com/project/team4backend/domain/member/repository/MemberRepository.java
  src/main/java/com/project/team4backend/domain/member/service/command/MemberCommandService.java
  src/main/java/com/project/team4backend/domain/member/service/command/MemberCommandServiceImpl.java
  src/main/java/com/project/team4backend/domain/member/service/query/MemberQueryService.java
  src/main/java/com/project/team4backend/domain/member/service/query/MemberQueryServiceImpl.java
Labels: ✨feature

#31 ♻️refactor: gpt 코드 계층에서 평면 구조로 변경 및 gpt api url 환경변수 해제
  src/main/resources/application.yml
Labels: ♻️refactor

#36 Feat/#15 s3 bucket 생성 이미지 업로드 삭제 api 구현
  build.gradle
  src/main/java/com/project/team4backend/Team4BackEndApplication.java
  src/main/java/com/project/team4backend/domain/auth/contoller/EmailVerificationController.java
  src/main/java/com/project/team4backend/domain/auth/service/RefreshTokenService.java
  src/main/java/com/project/team4backend/domain/auth/service/command/auth/AuthCommandServiceImpl.java
  src/main/java/com/project/team4backend/domain/auth/service/scheduler/EmailVerificationScheduler.java
  src/main/java/com/project/team4backend/domain/image/converter/ImageConverter.java
  src/main/java/com/project/team4backend/domain/image/dto/internel/ImageInternelDTO.java
  src/main/java/com/project/team4backend/domain/image/dto/request/ImageReqDTO.java
  src/main/java/com/project/team4backend/domain/image/dto/response/ImageResDTO.java
  src/main/java/com/project/team4backend/domain/image/exception/ImageErrorCode.java
  src/main/java/com/project/team4backend/domain/image/exception/ImageException.java
  src/main/java/com/project/team4backend/domain/image/service/RedisImageTracker.java
  src/main/java/com/project/team4backend/domain/image/service/command/ImageCommandService.java
  src/main/java/com/project/team4backend/domain/image/service/command/ImageCommandServiceImpl.java
  src/main/java/com/project/team4backend/domain/image/service/scheduler/ImageScheduler.java
  src/main/java/com/project/team4backend/domain/member/contoller/MemberController.java
  src/main/java/com/project/team4backend/domain/member/entity/Member.java
  src/main/java/com/project/team4backend/domain/member/repository/MemberRepository.java
  src/main/java/com/project/team4backend/domain/member/service/command/MemberCommandService.java
  src/main/java/com/project/team4backend/domain/member/service/command/MemberCommandServiceImpl.java
  src/main/java/com/project/team4backend/global/security/Config/RedisConfig.java
  src/main/java/com/project/team4backend/global/security/Config/S3Config.java
  src/main/java/com/project/team4backend/global/security/Config/SecurityConfig.java
  src/main/java/com/project/team4backend/global/security/handler/CustomLogoutHandler.java
  src/main/resources/application.yml
Labels: ✨feature

#39 Feat/#18 게시글 이미지 등록 관련 api
  src/main/java/com/project/team4backend/domain/image/converter/ImageConverter.java
  src/main/java/com/project/team4backend/domain/image/dto/internel/ImageInternelDTO.java
  src/main/java/com/project/team4backend/domain/image/dto/request/ImageReqDTO.java
  src/main/java/com/project/team4backend/domain/image/dto/response/ImageResDTO.java
  src/main/java/com/project/team4backend/domain/image/exception/ImageErrorCode.java
  src/main/java/com/project/team4backend/domain/image/service/RedisImageTracker.java
  src/main/java/com/project/team4backend/domain/image/service/command/ImageCommandService.java
  src/main/java/com/project/team4backend/domain/image/service/command/ImageCommandServiceImpl.java
  src/main/java/com/project/team4backend/domain/image/service/scheduler/ImageScheduler.java
  src/main/java/com/project/team4backend/domain/member/contoller/MemberController.java
  src/main/java/com/project/team4backend/domain/member/entity/Member.java
  src/main/java/com/project/team4backend/domain/member/service/command/MemberCommandService.java
  src/main/java/com/project/team4backend/domain/member/service/command/MemberCommandServiceImpl.java
  src/main/java/com/project/team4backend/domain/post/controller/PostController.java
  src/main/java/com/project/team4backend/domain/post/converter/PostConverter.java
  src/main/java/com/project/team4backend/domain/post/entity/Post.java
  src/main/java/com/project/team4backend/domain/post/entity/PostImage.java
  src/main/java/com/project/team4backend/domain/post/service/command/PostCommandServiceImpl.java
  src/main/java/com/project/team4backend/domain/post/service/query/PostQueryServiceImpl.java
Labels: ✨feature

#52 🐛fix: 프론트 연동 url CorsConfig에 추가 후 securityConfig filter에 적용
  src/main/java/com/project/team4backend/domain/auth/entity/SocialLogin.java
  src/main/java/com/project/team4backend/global/security/Config/CorsConfig.java
  src/main/java/com/project/team4backend/global/security/Config/SecurityConfig.java
Labels: 🐛fix

#56 🐛fix: 프론트 연동 url CorsConfig에 추가 후 securityConfig filter에 적용
  src/main/java/com/project/team4backend/domain/member/converter/MemberConverter.java
Labels: ♻️refactor

#63 ♻️refactor: 로그인 시 istemp 필드 추가
  src/main/java/com/project/team4backend/domain/auth/contoller/AuthController.java
  src/main/java/com/project/team4backend/domain/auth/dto/request/AuthReqDTO.java
  src/main/java/com/project/team4backend/domain/auth/dto/response/AuthResDTO.java
  src/main/java/com/project/team4backend/domain/auth/service/command/auth/AuthCommandService.java
  src/main/java/com/project/team4backend/domain/auth/service/command/auth/AuthCommandServiceImpl.java
  src/main/java/com/project/team4backend/global/security/filter/CustomLoginFilter.java
Labels: ♻️refactor

#64 ♻️refactor: 댓글에 부모 댓글 필드 추가
  src/main/java/com/project/team4backend/domain/comment/converter/CommentConverter.java
  src/main/java/com/project/team4backend/domain/comment/entity/Comment.java
  src/main/java/com/project/team4backend/domain/comment/service/command/CommentCommandServiceImpl.java
Labels: ♻️refactor
